project:
  type: website

website:
  title: "Sales_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      

format:
  html:
    css: styles.css
    toc: true
    
output:
  quarto::html_document:
    theme: vapor
      

editor: visual

